# =============================================
# GENERAL & AUTH
# =============================================

###
# @name adminLogin
# Admin Login
POST http://localhost:3001/api/staff/login
Content-Type: application/json

{
  "email": "testadmin@example.com",
  "password": "password"
}
