import { Subscriber } from "@/payload-types"

export const subscribers: Subscriber[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    accountNumber: "A001",
    mpesaNumber: "254712345678",
    status: "active",
    servicePlan: { id: "1", name: "Basic", downloadSpeed: 10, uploadSpeed: 5, price: 1000, billingCycle: "monthly", ipAssignmentType: "dynamic", planEnabled: true, activeForNewSignups: true, createdAt: "", updatedAt: "" },
    billingCycle: "monthly",
    nextDueDate: "2025-10-01",
    accountBalance: 0,
    createdAt: "2025-09-01",
    updatedAt: "2025-09-01",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    accountNumber: "A002",
    mpesaNumber: "254712345679",
    status: "pending-installation",
    servicePlan: { id: "2", name: "Premium", downloadSpeed: 50, uploadSpeed: 25, price: 3000, billingCycle: "monthly", ipAssignmentType: "dynamic", planEnabled: true, activeForNewSignups: true, createdAt: "", updatedAt: "" },
    billingCycle: "monthly",
    nextDueDate: "2025-10-01",
    accountBalance: 3000,
    createdAt: "2025-09-01",
    updatedAt: "2025-09-01",
  },
  {
    id: "3",
    firstName: "Peter",
    lastName: "Jones",
    accountNumber: "A003",
    mpesaNumber: "254712345680",
    status: "suspended",
    servicePlan: { id: "1", name: "Basic", downloadSpeed: 10, uploadSpeed: 5, price: 1000, billingCycle: "monthly", ipAssignmentType: "dynamic", planEnabled: true, activeForNewSignups: true, createdAt: "", updatedAt: "" },
    billingCycle: "monthly",
    nextDueDate: "2025-09-01",
    accountBalance: -1000,
    createdAt: "2025-08-01",
    updatedAt: "2025-09-01",
  },
]
