import { NetworkDevice } from "@/payload-types"

export const resources: NetworkDevice[] = [
  {
    id: "device1",
    deviceName: "Router 1",
    deviceType: "router",
    ipAddress: { id: "ip1", ipAddress: "192.168.1.1", type: "ipv4", createdAt: "", updatedAt: "" },
    physicalLocation: { id: "loc1", name: "Main Office", latitude: -1.286389, longitude: 36.817223, ispOwner: "1", createdAt: "", updatedAt: "" },
    monitoringType: "snmp",
    status: "active",
    purchaseDate: "2023-01-15T00:00:00.000Z",
    purchaseCost: 1200,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "device2",
    deviceName: "Switch 1",
    deviceType: "switch",
    ipAddress: { id: "ip2", ipAddress: "192.168.1.2", type: "ipv4", createdAt: "", updatedAt: "" },
    physicalLocation: { id: "loc2", name: "Branch Office", latitude: -1.292066, longitude: 36.821946, ispOwner: "1", createdAt: "", updatedAt: "" },
    monitoringType: "ping",
    status: "inactive",
    purchaseDate: "2023-02-20T00:00:00.000Z",
    purchaseCost: 800,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: "device3",
    deviceName: "Access Point 1",
    deviceType: "access-point",
    ipAddress: { id: "ip3", ipAddress: "192.168.1.3", type: "ipv4", createdAt: "", updatedAt: "" },
    physicalLocation: { id: "loc1", name: "Main Office", latitude: -1.286389, longitude: 36.817223, ispOwner: "1", createdAt: "", updatedAt: "" },
    monitoringType: "snmp",
    status: "maintenance",
    purchaseDate: "2023-03-10T00:00:00.000Z",
    purchaseCost: 300,
    createdAt: "",
    updatedAt: "",
  },
];
